{{- if .Values.istio.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        - admin-profile
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
{{ end }}