apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  basic.ini: |
    default_permission=MANAGE
    admin_username=admin
    admin_password=admin