{{ if .Values.mysql.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlflow.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{ end }}