
{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.secretName" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
data:
  {{- range $key, $value := .Values.secret.mysql }}
  {{ $key }} : {{ $value | b64enc }}
  {{- end }}